"""
Train a diffusion-time bulk modulus predictor using cached MatterGen datasets and optional
synthetic structures generated by the diffusion model (labeled with an oracle).

The model takes a noisy diffusion state (x_t, t) and predicts the bulk modulus
of the clean structure x_0. It shares the GemNet backbone and timestep encoding with the
denoiser so it can be dropped into sampling-time guidance.
"""

from __future__ import annotations

import argparse
import itertools
import tempfile
import zipfile
from dataclasses import asdict
from pathlib import Path
import os

import torch
import torch.nn.functional as F
from torch_geometric.loader import DataLoader as GeoDataLoader
from torch.utils.data import random_split
from tqdm import tqdm

from mattergen.common.data.chemgraph import ChemGraph
from mattergen.common.data.dataset import CrystalDataset
from mattergen.common.data.transform import symmetrize_lattice
from mattergen.common.diffusion.corruption import (
    LatticeVPSDE,
    NumAtomsVarianceAdjustedWrappedVESDE,
)
from mattergen.common.utils.data_classes import MatterGenCheckpointInfo
from mattergen.diffusion.corruption.d3pm_corruption import D3PMCorruption
from mattergen.diffusion.corruption.multi_corruption import MultiCorruption
from mattergen.diffusion.d3pm.d3pm import MaskDiffusion, create_discrete_diffusion_schedule
from mattergen.diffusion.timestep_samplers import UniformTimestepSampler
from mattergen.generator import CrystalGenerator
from mattergen.property_predictors import BulkModulusTimeClassifier
from mattergen.guidance.calc_bulk_modulus import run_bulk_modulus_oracle


def bulk_modulus_oracle(structure) -> float:
    """
    Wrapper around the QHA-based oracle. Uses a temporary directory to avoid
    clobbering outputs when called repeatedly.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        return run_bulk_modulus_oracle(structure, outdir=tmpdir)


def structure_to_chemgraph(struct) -> ChemGraph:
    frac_coords = torch.tensor(struct.frac_coords, dtype=torch.float32) % 1.0
    cell = torch.tensor(struct.lattice.matrix, dtype=torch.float32).unsqueeze(0)
    atomic_numbers = torch.tensor(struct.atomic_numbers, dtype=torch.long)
    num_atoms = torch.tensor(len(struct), dtype=torch.long)
    material_id = getattr(getattr(struct, "properties", None), "get", lambda _k, _d=None: None)(
        "material_id", None
    )
    return ChemGraph(
        pos=frac_coords,
        cell=cell,
        atomic_numbers=atomic_numbers,
        num_atoms=num_atoms,
        num_nodes=num_atoms,
        structure_id=material_id,
    )


def build_default_corruption() -> MultiCorruption:
    pos_sde = NumAtomsVarianceAdjustedWrappedVESDE(
        wrapping_boundary=1.0, sigma_min=0.01, sigma_max=5.0, limit_info_key="num_atoms"
    )
    cell_sde = LatticeVPSDE(
        beta_min=0.1,
        beta_max=20,
        limit_density=0.05,
        limit_var_scaling_constant=0.25,
    )
    atom_corruption = D3PMCorruption(
        offset=1,
        d3pm=MaskDiffusion(
            dim=101,
            schedule=create_discrete_diffusion_schedule(kind="standard", num_steps=1000),
        ),
    )
    return MultiCorruption(
        sdes={"pos": pos_sde, "cell": cell_sde},
        discrete_corruptions={"atomic_numbers": atom_corruption},
    )


def gaussian_nll(mu: torch.Tensor, logvar: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
    inv_var = torch.exp(-logvar)
    return 0.5 * ((mu - target) ** 2 * inv_var + logvar)


def run_epoch(
    *,
    model: BulkModulusTimeClassifier,
    loader: GeoDataLoader,
    corruption: MultiCorruption,
    timestep_sampler: UniformTimestepSampler,
    optimizer: torch.optim.Optimizer | None,
    device: torch.device,
    use_mse: bool,
    property_name: str,
    synthetic_loader: GeoDataLoader | None = None,
) -> float:
    is_train = optimizer is not None
    model.train(is_train)
    total_loss = 0.0
    n_batches = 0
    iter_loaders = itertools.chain(loader, synthetic_loader) if synthetic_loader is not None else loader
    for batch in tqdm(iter_loaders, desc="train" if is_train else "val"):
        batch = batch.to(device)
        if is_train:
            optimizer.zero_grad(set_to_none=True)

        targets = batch[property_name].detach().view(-1)
        t = timestep_sampler(batch_size=batch.get_batch_size(), device=device)
        noisy_batch = corruption.sample_marginal(batch, t)
        mu, logvar = model(noisy_batch, t)
        loss = F.mse_loss(mu, targets) if use_mse else gaussian_nll(mu, logvar, targets).mean()

        if is_train:
            loss.backward()
            optimizer.step()

        total_loss += loss.detach().item()
        n_batches += 1
    return total_loss / max(n_batches, 1)


def save_checkpoint(
    out_dir: Path,
    name: str,
    model: BulkModulusTimeClassifier,
    optimizer: torch.optim.Optimizer,
    epoch: int,
    cfg: dict,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "epoch": epoch,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "config": cfg,
        },
        out_dir / f"{name}.pt",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train bulk modulus diffusion-time classifier")
    parser.add_argument(
        "--train_cache_dir",
        type=str,
        default=str(Path(__file__).resolve().parents[2] / "data-release" / "alex-mp" / "train"),
        help="Path to cached train split. If present, takes priority over dataset_path.",
    )
    parser.add_argument(
        "--val_cache_dir",
        type=str,
        default=str(Path(__file__).resolve().parents[2] / "data-release" / "alex-mp" / "val"),
        help="Path to cached val split. If present, takes priority over dataset_path.",
    )
    parser.add_argument(
        "--dataset_path",
        type=str,
        default=str(Path(__file__).resolve().parents[2] / "data-release" / "alex-mp" / "alex_mp_20.zip"),
        help="Path to a single cached dataset archive/folder (no splits). Will be used if train/val dirs are missing.",
    )
    parser.add_argument(
        "--train_csv",
        type=str,
        default=str(Path(__file__).resolve().parents[2] / "data-release" / "mp-20" / "mp_20" / "train.csv"),
        help="Optional CSV for training split; if provided with val_csv, takes priority over cached dirs.",
    )
    parser.add_argument(
        "--val_csv",
        type=str,
        default=str(Path(__file__).resolve().parents[2] / "data-release" / "mp-20" / "mp_20" / "val.csv"),
        help="Optional CSV for validation split; if provided with train_csv, takes priority over cached dirs.",
    )
    parser.add_argument(
        "--csv_cache_root",
        type=str,
        default=str(Path(__file__).resolve().parents[2] / "data-release" / "mp-20" / "cache"),
        help="Where to cache numpy arrays when loading from CSVs.",
    )
    parser.add_argument(
        "--val_fraction",
        type=float,
        default=0.1,
        help="Validation fraction when splitting a single dataset (used if no explicit val cache).",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed for splitting.")
    parser.add_argument("--out_dir", type=str, required=True, help="Directory to store checkpoints")
    parser.add_argument(
        "--property_name",
        type=str,
        default="ml_bulk_modulus",
        help="Dataset property key to supervise on (e.g., ml_bulk_modulus or dft_bulk_modulus)",
    )
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--weight_decay", type=float, default=0.0)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--hidden_dim", type=int, default=512)
    parser.add_argument("--mlp_hidden_dim", type=int, default=256)
    parser.add_argument("--logvar_min", type=float, default=-10.0)
    parser.add_argument("--logvar_max", type=float, default=5.0)
    parser.add_argument("--use_mse", action="store_true", help="Fallback to MSE loss")
    # Synthetic augmentation via diffusion generator
    parser.add_argument(
        "--synthetic_model_path",
        type=str,
        default=None,
        help="Path to diffusion checkpoint dir for sampling synthetic structures (optional).",
    )
    parser.add_argument(
        "--synthetic_pretrained_name",
        type=str,
        default=None,
        help="HF pretrained name alternative to synthetic_model_path.",
    )
    parser.add_argument(
        "--synthetic_num_batches",
        type=int,
        default=0,
        help="How many synthetic batches to draw each epoch. Set 0 to disable.",
    )
    parser.add_argument(
        "--synthetic_batch_size",
        type=int,
        default=16,
        help="Batch size for synthetic generation.",
    )
    parser.add_argument(
        "--synthetic_sampling_config_name",
        type=str,
        default="default",
        help="Sampling config for synthetic generation.",
    )
    parser.add_argument(
        "--synthetic_guidance_factor",
        type=float,
        default=0.0,
        help="Existing conditional guidance factor to use when generating synthetic structures.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    transforms = [symmetrize_lattice]
    train_dataset, val_dataset, _tmp = load_datasets(args=args, transforms=transforms)

    train_loader = GeoDataLoader(
        train_dataset, batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers
    )
    val_loader = GeoDataLoader(
        val_dataset, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers
    )

    corruption = build_default_corruption()
    timestep_sampler = UniformTimestepSampler(min_t=1e-5, max_t=corruption.T)

    model = BulkModulusTimeClassifier(
        hidden_dim=args.hidden_dim,
        mlp_hidden_dim=args.mlp_hidden_dim,
        logvar_bounds=(args.logvar_min, args.logvar_max),
    ).to(device)
    optimizer = torch.optim.AdamW(
        model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay
    )

    best_val = float("inf")
    cfg = {
        "model_kwargs": asdict(model.init_config),
        "args": vars(args),
    }
    synthetic_info: MatterGenCheckpointInfo | None = None
    if args.synthetic_model_path or args.synthetic_pretrained_name:
        synthetic_info = (
            MatterGenCheckpointInfo.from_hf_hub(args.synthetic_pretrained_name)
            if args.synthetic_pretrained_name
            else MatterGenCheckpointInfo(
                model_path=Path(args.synthetic_model_path).resolve(),
                load_epoch="last",
                config_overrides=[],
            )
        )

    for epoch in range(1, args.epochs + 1):
        synthetic_loader = None
        if synthetic_info is not None and args.synthetic_num_batches > 0:
            synthetic_loader = build_synthetic_loader(
                info=synthetic_info,
                num_batches=args.synthetic_num_batches,
                batch_size=args.synthetic_batch_size,
                property_name=args.property_name,
                transforms=transforms,
                sampling_config_name=args.synthetic_sampling_config_name,
                diffusion_guidance_factor=args.synthetic_guidance_factor,
            )
        train_loss = run_epoch(
            model=model,
            loader=train_loader,
            corruption=corruption,
            timestep_sampler=timestep_sampler,
            optimizer=optimizer,
            device=device,
            use_mse=args.use_mse,
            property_name=args.property_name,
            synthetic_loader=synthetic_loader,
        )
        val_loss = run_epoch(
            model=model,
            loader=val_loader,
            corruption=corruption,
            timestep_sampler=timestep_sampler,
            optimizer=None,
            device=device,
            use_mse=args.use_mse,
            property_name=args.property_name,
        )
        print(f"epoch {epoch}: train_loss={train_loss:.4f} val_loss={val_loss:.4f}")

        save_checkpoint(
            Path(args.out_dir),
            name="last",
            model=model,
            optimizer=optimizer,
            epoch=epoch,
            cfg=cfg,
        )
        if val_loss < best_val:
            best_val = val_loss
            save_checkpoint(
                Path(args.out_dir),
                name="best",
                model=model,
                optimizer=optimizer,
                epoch=epoch,
                cfg=cfg,
            )


def build_synthetic_loader(
    *,
    info: MatterGenCheckpointInfo,
    num_batches: int,
    batch_size: int,
    property_name: str,
    transforms: list,
    sampling_config_name: str,
    diffusion_guidance_factor: float,
) -> GeoDataLoader:
    """
    Generate synthetic structures with a diffusion model, label via oracle, and wrap
    them into a GeoDataLoader for augmentation.
    """
    device = torch.get_device()
    with tempfile.TemporaryDirectory() as tmpdir:
        generator = CrystalGenerator(
            checkpoint_info=info,
            batch_size=batch_size,
            num_batches=num_batches,
            sampling_config_name=sampling_config_name,
            sampling_config_overrides=[],
            record_trajectories=False,
            diffusion_guidance_factor=diffusion_guidance_factor,
        )
        structures = generator.generate(output_dir=tmpdir)

    chemgraphs: list[ChemGraph] = []
    for struct in structures:
        cg = structure_to_chemgraph(struct)
        for t in transforms:
            cg = t(cg)
        label = torch.tensor(bulk_modulus_oracle(struct), dtype=torch.float32).view(1)
        cg = cg.replace(**{property_name: label})
        chemgraphs.append(cg)

    return GeoDataLoader(
        chemgraphs,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
    )


def _maybe_extract_dataset(path: Path) -> tuple[Path, tempfile.TemporaryDirectory | None]:
    """
    If path is a zip archive (including git-lfs pointer once downloaded), extract to temp dir.
    Returns (cache_path, tmpdir_or_None).
    """
    if path.is_dir():
        return path, None
    if not path.exists():
        raise FileNotFoundError(f"Dataset path not found: {path}")
    if zipfile.is_zipfile(path):
        tmpdir = tempfile.TemporaryDirectory()
        with zipfile.ZipFile(path, "r") as zf:
            zf.extractall(tmpdir.name)
        return Path(tmpdir.name), tmpdir
    raise ValueError(f"Unsupported dataset path: {path}")


def _has_cache_files(folder: Path) -> bool:
    return (folder / "pos.npy").exists() and (folder / "cell.npy").exists()


def load_datasets(args, transforms):
    """
    Load train/val datasets. If explicit train/val cache dirs exist, use them.
    Otherwise, if train/val CSVs are provided, cache them and load.
    Otherwise, load a single dataset archive/folder and split into train/val,
    or use provided train/val subfolders if they exist in the archive.
    Returns (train_dataset, val_dataset, tmpdir_or_None) so caller can keep tmp alive.
    """
    props = [args.property_name]
    train_dir = Path(args.train_cache_dir)
    val_dir = Path(args.val_cache_dir)
    if _has_cache_files(train_dir) and _has_cache_files(val_dir):
        return (
            CrystalDataset.from_cache_path(cache_path=train_dir, properties=props, transforms=transforms),
            CrystalDataset.from_cache_path(cache_path=val_dir, properties=props, transforms=transforms),
            None,
        )

    # If CSVs are provided, cache them and use that.
    if args.train_csv and args.val_csv:
        csv_cache_root = Path(args.csv_cache_root)
        train_cache = csv_cache_root / "train"
        val_cache = csv_cache_root / "val"
        train_cache.mkdir(parents=True, exist_ok=True)
        val_cache.mkdir(parents=True, exist_ok=True)
        train_dataset = CrystalDataset.from_csv(
            csv_path=args.train_csv,
            cache_path=str(train_cache),
            transforms=transforms,
        )
        val_dataset = CrystalDataset.from_csv(
            csv_path=args.val_csv,
            cache_path=str(val_cache),
            transforms=transforms,
        )
        return train_dataset, val_dataset, None

    cache_root, tmpdir = _maybe_extract_dataset(Path(args.dataset_path))
    # If archive already contains train/val subfolders, use them.
    if (cache_root / "train").exists() and (cache_root / "val").exists():
        return (
            CrystalDataset.from_cache_path(cache_path=cache_root / "train", properties=props, transforms=transforms),
            CrystalDataset.from_cache_path(cache_path=cache_root / "val", properties=props, transforms=transforms),
            tmpdir,
        )

    if not _has_cache_files(cache_root):
        raise FileNotFoundError(
            f"No cache files found in {cache_root}. Expected pos.npy/cell.npy/etc. "
            "Download or unpack the cached dataset first."
        )

    full = CrystalDataset.from_cache_path(cache_path=cache_root, properties=props, transforms=transforms)
    val_size = max(1, int(len(full) * args.val_fraction))
    train_size = len(full) - val_size
    generator = torch.Generator().manual_seed(args.seed)
    train_dataset, val_dataset = random_split(full, [train_size, val_size], generator=generator)
    return train_dataset, val_dataset, tmpdir


if __name__ == "__main__":
    main()
